$DeviceRolesAPIPath="dcim/device-roles"
$deviceTypesPath="dcim/device-types"
$DevicesAPIPath="dcim/devices"
$NBDeviceInterfaceAPIPath="dcim/interfaces"
$LocationsAPIPath="dcim/locations"
$ManufacturerAPIPath="dcim/manufacturers"
$DevicePlatformAPIPath="dcim/platforms"
$RacksAPIPath="dcim/racks"
$RackReservationsAPIPath="dcim/rack-reservations"
$RackRolesAPIPath="dcim/rack-roles"
$RacksAPIPath="dcim/racks"
$regionsAPIPath="dcim/regions"
$SiteGroupsAPIPath="dcim/site-groups"
$SitesAPIPath="dcim/sites"
$NBVirtualChassisAPIPath="dcim/virtual-chassis"
$NBAggregateAPIPath="ipam/aggregates"
$ASNsAPIPath="ipam/asns"
$IPAddressAPIPath="ipam/ip-addresses"
$IPRangesAPIPath="ipam/ip-ranges"
$PrefixesAPIPath="ipam/prefixes"
$RIRsAPIPath="ipam/rirs"
$IPAMRolesAPIPath="ipam/roles"
$NBServiceAPIPath="ipam/services"
$vlangroupsAPIPath="ipam/vlan-groups"
$VLANsAPIPath="ipam/vlans"
$VRFsApiPath="ipam/vrfs"
$StatusAPIPath="status"
$ContactGroupsAPIPath="tenancy/contact-groups"
$ContactRolesAPIPath="tenancy/contact-roles"
$ContactsAPIPath="tenancy/contacts"
$TenantGroupsAPIPath="tenancy/tenant-groups"
$TenantsAPIPath="tenancy/tenants"
$UsersAPIPath="users/users"
$VirtualizationClusterGroupsAPIPath="virtualization/cluster-groups"
$VirtualizationClusterTypesAPIPath="virtualization/cluster-types"
$VirtualizationClustersAPIPath="virtualization/clusters"
$VirtualizationInterfaceAPIPath="virtualization/interfaces"
$VirtualizationVMsAPIPath="virtualization/virtual-machines"
$NBWirelessLanGroupAPIPath="wireless/wireless-lan-groups"
$NBWirelessLanAPIPath="wireless/wireless-lans"
$NBWirelessLinkAPIPath="wireless/wireless-links"
# 0.0.5
$NBTagsAPIPath="extras/tags"
$NBObjectTypesAPIPath="extras/object-types"
$NBCircuitProvidersAPIPath="circuits/providers"
$NBCircuitProviderNetworksAPIPath="circuits/provider-networks"
$NBCircuitProviderAccountsAPIPath="circuits/provider-accounts"
$NBCircuitTypesAPIPath="circuits/circuit-types"
$NBCircuitsAPIPath="circuits/circuits"
$NBCircuitTerminationsAPIPath="circuits/circuit-terminations"
$NBServiceTemplatesAPIPath="ipam/service-templates"
$NBPowerPanelsAPIPath="dcim/power-panels"
$NBPowerFeedsAPIPath="dcim/power-feeds"

# 0.0.8

$NBCircuitGroupAssignmentsAPIPath="circuits/circuit-group-assignments"
$NBCircuitGroupsAPIPath="circuits/circuit-groups"
$NBCablesAPIPath="dcim/cables"
$NBCableTerminationsAPIPath="dcim/cable-terminations"
$NBPowerOutletsAPIPath='dcim/power-outlets'
$NBRackTypesAPIPath='dcim/rack-types'
$NBVirtualDisksAPIPath='virtualization/virtual-disks'

# 1.0.0

$NBVirtualCircuitTerminationsAPIPath="circuits/virtual-circuit-terminations"
$NBVirtualCircuitTypessAPIPath="circuits/virtual-circuit-types"
$NBVirtualCircuitsAPIPath="circuits/virtual-circuits"
$MACAddressAPIPath="dcim/mac-addresses"
$PowerPortAPIPath="dcim/power-ports"